// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'C:/Users/HP/Desktop/sch/sch/src/models/app';
import model_2 from 'C:/Users/HP/Desktop/sch/sch/src/models/base/comic';
import model_3 from 'C:/Users/HP/Desktop/sch/sch/src/models/base/userManage';
import model_4 from 'C:/Users/HP/Desktop/sch/sch/src/models/System/dataManage';
import model_5 from 'C:/Users/HP/Desktop/sch/sch/src/models/System/loginLog';
import model_6 from 'C:/Users/HP/Desktop/sch/sch/src/models/System/logs/exceptionLog';
import model_7 from 'C:/Users/HP/Desktop/sch/sch/src/models/System/opertation';
import model_8 from 'C:/Users/HP/Desktop/sch/sch/src/models/System/permissions/organization';
import model_9 from 'C:/Users/HP/Desktop/sch/sch/src/models/System/permissions/role';
import model_10 from 'C:/Users/HP/Desktop/sch/sch/src/models/System/permissions/theme';
import model_11 from 'C:/Users/HP/Desktop/sch/sch/src/models/System/permissions/user';
import model_12 from 'C:/Users/HP/Desktop/sch/sch/src/models/Welcome';

export const models = {
model_1: { namespace: 'app', model: model_1 },
model_2: { namespace: 'base.comic', model: model_2 },
model_3: { namespace: 'base.userManage', model: model_3 },
model_4: { namespace: 'System.dataManage', model: model_4 },
model_5: { namespace: 'System.loginLog', model: model_5 },
model_6: { namespace: 'System.logs.exceptionLog', model: model_6 },
model_7: { namespace: 'System.opertation', model: model_7 },
model_8: { namespace: 'System.permissions.organization', model: model_8 },
model_9: { namespace: 'System.permissions.role', model: model_9 },
model_10: { namespace: 'System.permissions.theme', model: model_10 },
model_11: { namespace: 'System.permissions.user', model: model_11 },
model_12: { namespace: 'Welcome', model: model_12 },
} as const
