export const menuTree = [
  {
    menuId: 1,
    menuName: '系统管理',
    menuLevel: 1,
    menuParId: null,
    menuType: 'root',
    menuIndex: 1,
    menuRemark: '系统管理',
    icon: null,
    menuAddr: null,
    isInvalid: false,
    perssionType: 0,
    permissionCode: null,
    children: [
      {
        menuId: 297,
        menuName: '用户管理',
        menuLevel: 2,
        menuParId: 1,
        menuType: null,
        menuIndex: 0,
        menuRemark: null,
        icon: null,
        menuAddr: "/userManage",
        isInvalid: false,
        perssionType: 3,
        permissionCode: null,
        children: null,
        // children: [
        //   {
        //     menuId: 298,
        //     menuName: '报告列表',
        //     menuLevel: 2,
        //     menuParId: 297,
        //     menuType: null,
        //     menuIndex: 0,
        //     menuRemark: null,
        //     icon: null,
        //     menuAddr: '/page5',
        //     isInvalid: false,
        //     perssionType: 0,
        //     permissionCode: null,
        //     children: null,
        //     hasChildren: null,
        //   },
        //   {
        //     menuId: 299,
        //     menuName: '数据管理',
        //     menuLevel: 2,
        //     menuParId: 297,
        //     menuType: null,
        //     menuIndex: 0,
        //     menuRemark: null,
        //     icon: null,
        //     menuAddr: '/userManage',
        //     isInvalid: false,
        //     perssionType: 0,
        //     permissionCode: null,
        //     hasChildren: true,
        //     children: [
        //       {
        //         menuId: 300,
        //         menuName: '车辆数据',
        //         menuLevel: 3,
        //         menuParId: 297,
        //         menuType: null,
        //         menuIndex: 0,
        //         menuRemark: null,
        //         icon: null,
        //         menuAddr: '/carData',
        //         isInvalid: false,
        //         perssionType: 0,
        //         permissionCode: null,
        //         children: null,
        //         hasChildren: null,
        //       },
        //       {
        //         menuId: 301,
        //         menuName: '路侧数据',
        //         menuLevel: 3,
        //         menuParId: 297,
        //         menuType: null,
        //         menuIndex: 0,
        //         menuRemark: null,
        //         icon: null,
        //         menuAddr: '/laneSide',
        //         isInvalid: false,
        //         perssionType: 0,
        //         permissionCode: null,
        //         children: null,
        //         hasChildren: null,
        //       },
        //     ],
        //   },
        // ],
        hasChildren: false,
      },
      {
        menuId: 384,
        menuName: '番剧管理',
        menuLevel: 2,
        menuParId: 1,
        menuType: null,
        menuIndex: 5,
        menuRemark: null,
        icon: null,
        menuAddr: '/comic',
        isInvalid: false,
        perssionType: 3,
        permissionCode: null,
        children: null,
        hasChildren: true,
      }
    ],
    hasChildren: true,
  },
];
