// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'C:/Users/HP/Desktop/sch/sch/node_modules/.pnpm/@umijs+renderer-react@4.0.53_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from 'C:/Users/HP/Desktop/sch/sch/node_modules/.pnpm/@umijs+renderer-react@4.0.53_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'C:/Users/HP/Desktop/sch/sch/node_modules/.pnpm/umi@4.0.53_@babel+core@7.21.0_@types+react@17.0.53_eslint@8.35.0_postcss@8.4.21_prettier@2.8._ugibm3dewn6hqpag6abrawns6a/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { connect, useDispatch, useStore, useSelector, getDvaApp } from 'C:/Users/HP/Desktop/sch/sch/src/.umi/plugin-dva';
// plugins types.d.ts
export * from 'C:/Users/HP/Desktop/sch/sch/src/.umi/plugin-dva/types.d';
